const API_KEY = 'AIzaSyBb6CingEJiFVKG9HLgqs02tYq975XDFL0'
const SECRET_ACCESS_KEY = 'h4ho626wXwsEgTnYxTp93aKdCHyCgSc23NVGBQiz'
const ACCESS_KEY_ID = 'AKIAJJDRFYCFSUOT7JKQ'
const REGION = 'us-east-2'
const API_URL = 'http://68.183.121.88:3000'

export {
  API_KEY,
  SECRET_ACCESS_KEY,
  ACCESS_KEY_ID,
  REGION,
  API_URL
}