const API_KEY = 'AIzaSyB617c913tGwIqGRPLrMY0OfYQlBHLzIsY'
const SECRET_ACCESS_KEY = 'FwzXgdmI2kPUUtPXetL5Y0YH0ZEyEJDYfKLtNgqi'
const ACCESS_KEY_ID = 'AKIAJWZNFGR6XJJCUXBA'
const REGION = 'us-east-2'
const API_URL = 'http://68.183.121.88:3000'

export {
  API_KEY,
  SECRET_ACCESS_KEY,
  ACCESS_KEY_ID,
  REGION,
  API_URL
}